import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class SCNMatriculaERelatorioComErrante extends Simulation {
	
val httpProtocol = http
		.baseURL("https://guriensino.unipampa.edu.br")
		.inferHtmlResources()
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-GB,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0")

	val headers_0 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Upgrade-Insecure-Requests" -> "1")

	val headers_1 = Map("Accept" -> "text/css,*/*;q=0.1")

	val headers_10 = Map(
		"Accept-Encoding" -> "gzip, deflate",
		"Pragma" -> "no-cache")

	val headers_55 = Map("Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")

	val headers_57 = Map(
		"Content-Type" -> "application/x-www-form-urlencoded; charset=UTF-8",
		"X-Requested-With" -> "XMLHttpRequest")
	val headers_143 = Map(
		"Accept" -> "application/json, text/javascript, */*; q=0.01",
		"Content-Type" -> "application/x-www-form-urlencoded; charset=UTF-8",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_152 = Map("X-Requested-With" -> "XMLHttpRequest")

	val headers_153 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Content-Type" -> "multipart/form-data; boundary=---------------------------18809947177064580321660626423",
		"Upgrade-Insecure-Requests" -> "1")
	val uri1 = "guriensino.unipampa.edu.br"
    	val uri2 = "http://detectportal.firefox.com/success.txt"
    	val uri3 = "https://fonts.googleapis.com/css"
   	val matriculaCSV = csv("matriculas.csv").circular
	val solicitacaoCSV = csv("dadosSolicitacao.csv").circular 
	

	object Login {
		val scnLogin = exec(http("request_0")
			.get("/guri/")
			.headers(headers_0)
			.resources(http("request_1")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_2")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_3")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_4")
			.get("/guri/application/modules/ptl//views/public/css/carrossel.css")
			.headers(headers_1),
            http("request_5")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_6")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_7")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_8")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_9")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_10")
			.get(uri2 + "")
			.headers(headers_10),
            http("request_11")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_12")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_13")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_14")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_15")
			.get("/guri/public/js/angular.min.js"),
            http("request_16")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_17")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_18")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_19")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
            http("request_20")
			.get("/guri/public/js/admin.js"),
            http("request_21")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_22")
			.get("/guri/public/js/acessivel.js"),
            http("request_23")
			.get("/guri/public/js/validacoes.js"),
            http("request_24")
			.get("/guri/public/js/tabs.min.js"),
            http("request_25")
			.get("/guri/public/js/tabs.js"),
            http("request_26")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_27")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_28")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_29")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_30")
			.get("/guri/application/modules/ptl//views/public/js/carrossel.js"),
            http("request_31")
			.get("/guri/application/modules/ptl//views/public/js/login.js"),
            http("request_32")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_33")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_34")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_35")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_36")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_37")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_38")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_39")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_40")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_41")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_42")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_43")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_44")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_45")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_46")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_47")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_48")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_49")
			.get("/guri/public/themes/moder/imgs/instrucoes.png"),
            http("request_50")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_51")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_52")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_53")
			.get("/guri/public/themes/moder//imgs/lock.png"),
            http("request_54")
			.get("/guri/public/themes/moder//imgs/novo_user.png"),
            http("request_55")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55)))
		.pause(9)
		.feed(matriculaCSV)
		.exec(http("request_56")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.resources(http("request_57")
			.post("/guri/ptl/sistema/login")
			.headers(headers_57)
			.formParam("login", "${matriculas}")
			.formParam("senha", "123")
			.formParam("captcha", ""),
            http("request_58")
			.get("/guri/ptl/sistema/principal")
			.headers(headers_0),
            http("request_59")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_60")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_61")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_62")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_63")
			.get("/guri/application/modules/ptl/views/public/css/carrossel.css")
			.headers(headers_1),
            http("request_64")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_65")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_66")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_67")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_68")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_69")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_70")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_71")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_72")
			.get(uri2 + "")
			.headers(headers_10),
            http("request_73")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
            http("request_74")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_75")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_76")
			.get("/guri/public/js/angular.min.js"),
            http("request_77")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_78")
			.get("/guri/public/js/acessivel.js"),
            http("request_79")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_80")
			.get("/guri/public/js/admin.js"),
            http("request_81")
			.get("/guri/public/js/tabs.js"),
            http("request_82")
			.get("/guri/public/js/validacoes.js"),
            http("request_83")
			.get("/guri/public/js/tabs.min.js"),
            http("request_84")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_85")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_86")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_87")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_88")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_89")
			.get("/guri/application/modules/ptl/views/public/js/carrossel.js"),
            http("request_90")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png"),
            http("request_91")
			.get("/guri/public/themes/moder/imgs/situacao_livro.png"),
            http("request_92")
			.get("/guri/public/themes/moder/imgs/user.png"),
            http("request_93")
			.get("/guri/public/themes/moder/imgs/consultar_processo.png"),
            http("request_94")
			.get("/guri/public/themes/moder/imgs/painel_aluno_24.png"),
            http("request_95")
			.get("/guri/public/themes/moder/imgs/logo_guri.jpg"),
            http("request_96")
			.get("/guri/public/themes/moder/imgs/inicial_restaurante.png"),
            http("request_97")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_98")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_99")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_100")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_101")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_102")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_103")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_104")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_105")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_106")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_107")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_108")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_109")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_110")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_111")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_112")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_113")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_114")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_115")
			.get("/guri/public/themes/moder//imgs/diagonals_5.png"),
            http("request_116")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_117")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55)))

	}


	object Solicitacao {
		val scnSolicitarMatricula = exec(http("request_0")
			.get("/guri/pta/painel/")
			.headers(headers_0)
			.resources(http("request_1")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_2")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_3")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_4")
			.get("/guri/application/modules/pta/views/public/css/painel.css")
			.headers(headers_1),
            http("request_5")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_6")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_7")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_8")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_9")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_10")
			.get(uri2 + "")
			.headers(headers_10),
            http("request_11")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_12")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_13")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_14")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
            http("request_15")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_16")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_17")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_18")
			.get("/guri/public/js/acessivel.js"),
            http("request_19")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_20")
			.get("/guri/public/js/validacoes.js"),
            http("request_21")
			.get("/guri/public/js/admin.js"),
            http("request_22")
			.get("/guri/public/js/tabs.js"),
            http("request_23")
			.get("/guri/public/js/tabs.min.js"),
            http("request_24")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_25")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_26")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_27")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_28")
			.get("/guri/public/js/angular.min.js"),
            http("request_29")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_30")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_31")
			.get("/guri/public/themes/moder/imgs/user.png"),
            http("request_32")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_33")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_34")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_35")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_36")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_37")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_38")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png"),
            http("request_39")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_40")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_41")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_42")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_43")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_44")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_45")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_46")
			.get("/guri/public/themes/moder//imgs/home_32.png"),
            http("request_47")
			.get("/guri/application/modules/pta/views/public/imgs/solicit_matricula_48.png"),
            http("request_48")
			.get("/guri/application/modules/pta/views/public/imgs/trancamento_48_disabled.png"),
            http("request_49")
			.get("/guri/application/modules/pta/views/public/imgs/trancamento_parcial_48_disabled.png"),
            http("request_50")
			.get("/guri/application/modules/pta/views/public/imgs/edit_big_48.png"),
            http("request_51")
			.get("/guri/application/modules/pta/views/public/imgs/cracha_48.png"),
            http("request_52")
			.get("/guri/application/modules/pta/views/public/imgs/altera_dados_48.png"),
            http("request_53")
			.get("/guri/application/modules/pta/views/public/imgs/plano_ensino_48.png"),
            http("request_54")
			.get("/guri/application/modules/pta/views/public/imgs/diario_classe_48.png"),
            http("request_55")
			.get("/guri/application/modules/pta/views/public/imgs/relatorios_48.png"),
            http("request_56")
			.get("/guri/application/modules/pta/views/public/imgs/relatorios.png"),
            http("request_57")
			.get("/guri/application/modules/pta/views/public/imgs/quadro_horarios_48.png"),
            http("request_58")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_59")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_60")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_61")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_62")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_63")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_64")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55)))
		.pause(1)
		.exec(http("request_65")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.resources(http("request_66")
			.get("/guri/pta/solicitar_matricula/")
			.headers(headers_0),
            http("request_67")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_68")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_69")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_70")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_71")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_72")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_73")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_74")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_75")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_76")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_77")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_78")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_79")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_80")
			.get("/guri/public/js/acessivel.js"),
            http("request_81")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_82")
			.get(uri2 + "")
			.headers(headers_10),
            http("request_83")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
            http("request_84")
			.get("/guri/public/js/validacoes.js"),
            http("request_85")
			.get("/guri/public/js/tabs.js"),
            http("request_86")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_87")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_88")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_89")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_90")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_91")
			.get("/guri/public/js/angular.min.js"),
            http("request_92")
			.get("/guri/public/js/tabs.min.js"),
            http("request_93")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_94")
			.get("/guri/application/modules/pta/views/public/js/matricula.js"),
            http("request_95")
			.get("/guri/public/js/admin.js"),
            http("request_96")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_97")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_98")
			.get("/guri/public/themes/moder/imgs/user.png"),
            http("request_99")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_100")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_101")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_102")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_103")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_104")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_105")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_106")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_107")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_108")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_109")
			.get("/guri/public/themes/moder//imgs/seta_voltar_32.png"),
            http("request_110")
			.get("/guri/public/themes/moder//imgs/home_32.png"),
            http("request_111")
			.get("/guri/public/themes/moder/imgs/minus.gif"),
            http("request_112")
			.get("/guri/public/themes/moder//imgs/seta_baixo_16.png"),
            http("request_113")
			.get("/guri/public/themes/moder//imgs/ajax-loader-preto.gif"),
            http("request_114")
			.get("/guri/public/themes/moder//imgs/aviso_16.png"),
            http("request_115")
			.get("/guri/public/themes/moder//imgs/clock_16.png"),
            http("request_116")
			.get("/guri/public/themes/moder/imgs/plus.gif"),
            http("request_117")
			.get("/guri/public/themes/moder//imgs/search.png"),
            http("request_118")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_119")
			.get("/guri/public/themes/moder//imgs/seta_sobe_16_disabled.png"),
            http("request_120")
			.get("/guri/public/themes/moder//imgs/seta_desce_16_disabled.png"),
            http("request_121")
			.get("/guri/public/themes/moder//imgs/delete_16_disabled.png"),
            http("request_122")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png"),
            http("request_123")
			.get("/guri/public/themes/moder//imgs/seta_sobe_16.png"),
            http("request_124")
			.get("/guri/public/themes/moder//imgs/delete_16.png"),
            http("request_125")
			.get("/guri/public/themes/moder//imgs/seta_desce_16.png"),
            http("request_126")
			.get("/guri/public/themes/moder/imgs/seta_sobe_16_disabled.png"),
            http("request_127")
			.get("/guri/public/themes/moder/imgs/seta_desce_16_disabled.png"),
            http("request_128")
			.get("/guri/public/themes/moder//imgs/salvar_32.png"),
            http("request_129")
			.get("/guri/public/themes/moder//imgs/cancel_32.png"),
            http("request_130")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_131")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_132")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_133")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_134")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_135")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_136")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_137")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55)))
		.pause(2)
		.feed(solicitacaoCSV)
		.pause(6)
		.repeat(2006){
			doIfEquals("${matriculas}", "${matriculaSolicitacao}") {
  			exec(http("request_144")
			.post("/guri/pta/solicitar_matricula/atuSolicit")
			.headers(headers_57)
			.formParam("idTurma", "${idTurma}")
			.formParam("tipo", "A")
			.formParam("disc", "${disc}")
			.resources(http("request_145")
			.post("/guri/pta/solicitar_matricula/refreshColisoes")
			.headers(headers_143)
			.formParam("turmas", "0,${idTurma}")))
			}
		.feed(solicitacaoCSV)
		}
		.pause(2)
		.exec(http("request_146")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-soft_15_5f8168_1x100.png")
			.resources(http("request_147")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png"),
            http("request_148")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_ffffff_256x240.png"),
            http("request_149")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-hard_100_eeeeee_1x100.png"),
            http("request_150")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_dots-small_65_bcbdbc_2x2.png")))
		.pause(3)
		.exec(http("request_151")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-hard_100_f6f6f6_1x100.png")
			.resources(http("request_152")
			.post("/guri/ptl/sistema/isLogado")
			.headers(headers_152),
            http("request_153")
			.post("/guri/pta/solicitar_matricula/validarGravacao")
			.headers(headers_153)
			.body(RawFileBody("testeSo_0153_request.txt")),
            http("request_154")
			.get("/guri/pta/solicitar_matricula/")
			.headers(headers_0),
            http("request_155")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_156")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_157")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_158")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_159")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_160")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_161")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_162")
			.get("/guri/public/js/angular.min.js"),
            http("request_163")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_164")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_165")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_166")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_167")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_168")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_169")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
            http("request_170")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_171")
			.get("/guri/public/js/acessivel.js"),
            http("request_172")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_173")
			.get(uri2 + "")
			.headers(headers_10),
            http("request_174")
			.get("/guri/public/js/admin.js"),
            http("request_175")
			.get("/guri/public/js/validacoes.js"),
            http("request_176")
			.get("/guri/public/js/tabs.js"),
            http("request_177")
			.get("/guri/public/js/tabs.min.js"),
            http("request_178")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_179")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_180")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_181")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_182")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_183")
			.get("/guri/application/modules/pta/views/public/js/matricula.js"),
            http("request_184")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_185")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_186")
			.get("/guri/public/themes/moder/imgs/user.png"),
            http("request_187")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_188")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_189")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_190")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_191")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png"),
            http("request_192")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_193")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_194")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_195")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_196")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_197")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_198")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_199")
			.get("/guri/public/themes/moder//imgs/seta_voltar_32.png"),
            http("request_200")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_201")
			.get("/guri/public/themes/moder//imgs/home_32.png"),
            http("request_202")
			.get("/guri/public/themes/moder/imgs/minus.gif"),
            http("request_203")
			.get("/guri/public/themes/moder//imgs/ajax-loader-preto.gif"),
            http("request_204")
			.get("/guri/public/themes/moder//imgs/seta_baixo_16.png"),
            http("request_205")
			.get("/guri/public/themes/moder/imgs/plus.gif"),
            http("request_206")
			.get("/guri/public/themes/moder//imgs/clock_16.png"),
            http("request_207")
			.get("/guri/public/themes/moder//imgs/aviso_16.png"),
            http("request_208")
			.get("/guri/public/themes/moder//imgs/seta_desce_16_disabled.png"),
            http("request_209")
			.get("/guri/public/themes/moder//imgs/seta_sobe_16_disabled.png"),
            http("request_210")
			.get("/guri/public/themes/moder//imgs/delete_16_disabled.png"),
            http("request_211")
			.get("/guri/public/themes/moder//imgs/seta_sobe_16.png"),
            http("request_212")
			.get("/guri/public/themes/moder//imgs/seta_desce_16.png"),
            http("request_213")
			.get("/guri/public/themes/moder//imgs/delete_16.png"),
            http("request_214")
			.get("/guri/public/themes/moder/imgs/seta_sobe_16.png"),
            http("request_215")
			.get("/guri/public/themes/moder/imgs/seta_desce_16_disabled.png"),
            http("request_216")
			.get("/guri/public/themes/moder/imgs/seta_desce_16.png"),
            http("request_217")
			.get("/guri/public/themes/moder//imgs/salvar_32.png"),
            http("request_218")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_219")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_220")
			.get("/guri/public/themes/moder//imgs/cancel_32.png"),
            http("request_221")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_222")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_223")
			.get("/guri/public/themes/moder//imgs/search.png"),
            http("request_224")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_225")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_226")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55),
            http("request_227")
			.get("/guri/public/themes/moder/imgs/seta_sobe_16_disabled.png")))

			.exec(http("request_0")
			.get("https://" + uri1 + ":443/guri/")
			.headers(headers_0)
			.resources(http("request_1")
			.get("https://" + uri1 + ":443/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_2")
			.get("https://" + uri1 + ":443/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1)))	}

	object Relatorio{
		val scngerarRelatorio = exec(http("request_0")
			.get("/guri/pta/painel/")
			.headers(headers_0)
			.resources(http("request_1")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_2")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_3")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_4")
			.get("/guri/application/modules/pta/views/public/css/painel.css")
			.headers(headers_1),
            http("request_5")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_6")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_7")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_8")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_9")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_10")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_11")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_12")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_13")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_14")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_15")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_17")
			.get("/guri/public/js/acessivel.js"),
            http("request_18")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_19")
			.get("/guri/public/js/admin.js"),
            http("request_20")
			.get("/guri/public/js/angular.min.js"),
            http("request_21")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
            http("request_22")
			.get("/guri/public/js/validacoes.js"),
            http("request_23")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_24")
			.get("/guri/public/js/tabs.js"),
            http("request_25")
			.get("/guri/public/js/tabs.min.js"),
            http("request_26")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_27")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_28")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_29")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_30")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_31")
			.get("/guri/application/modules/pta/views/public/imgs/edit_big_48.png"),
            http("request_32")
			.get("/guri/application/modules/pta/views/public/imgs/solicit_matricula_48.png"),
            http("request_33")
			.get("/guri/application/modules/pta/views/public/imgs/cracha_48.png"),
            http("request_34")
			.get("/guri/application/modules/pta/views/public/imgs/trancamento_parcial_48_disabled.png"),
            http("request_35")
			.get("/guri/application/modules/pta/views/public/imgs/trancamento_48_disabled.png"),
            http("request_36")
			.get("/guri/application/modules/pta/views/public/imgs/altera_dados_48.png"),
            http("request_37")
			.get("/guri/application/modules/pta/views/public/imgs/relatorios.png"),
            http("request_38")
			.get("/guri/application/modules/pta/views/public/imgs/relatorios_48.png"),
            http("request_39")
			.get("/guri/application/modules/pta/views/public/imgs/diario_classe_48.png"),
            http("request_40")
			.get("/guri/application/modules/pta/views/public/imgs/quadro_horarios_48.png"),
            http("request_41")
			.get("/guri/application/modules/pta/views/public/imgs/plano_ensino_48.png"),
            http("request_42")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_43")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_44")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_45")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_46")
			.get("/guri/public/themes/moder/imgs/user.png"),
            http("request_47")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_48")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_49")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_50")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_51")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png"),
            http("request_52")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_53")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_54")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_55")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_56")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_57")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_58")
			.get("/guri/public/themes/moder//imgs/home_32.png"),
            http("request_59")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_60")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_61")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_62")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_63")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_64")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55)))
		.pause(1)
		.exec(http("request_65")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.resources(http("request_66")
			.get("/guri/pta/relatorios/listar/")
			.headers(headers_0),
            http("request_67")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_68")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_69")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_70")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_71")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_72")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_73")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_74")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_75")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_76")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_77")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_78")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_79")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_80")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_81")
			.get("/guri/public/js/acessivel.js"),
            http("request_82")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_83")
			.get("/guri/public/js/admin.js"),
            http("request_84")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_85")
			.get("/guri/public/js/validacoes.js"),
            http("request_86")
			.get("/guri/public/js/angular.min.js"),
            http("request_87")
			.get("/guri/public/js/tabs.js"),
            http("request_88")
			.get("/guri/public/js/tabs.min.js"),
            http("request_89")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
           	http("request_91")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_92")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_93")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_94")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_95")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_96")
			.get("/guri/public/themes/moder//imgs/pdf_16.png"),
            http("request_97")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_98")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_99")
			.get("/guri/public/themes/moder/imgs/user.png"),
            http("request_100")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_101")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_102")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_103")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_104")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_105")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_106")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png"),
            http("request_107")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_108")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_109")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_110")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_111")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_112")
			.get("/guri/public/themes/moder//imgs/seta_voltar_32.png"),
            http("request_113")
			.get("/guri/public/themes/moder//imgs/home_32.png"),
            http("request_114")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_115")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_116")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_117")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_118")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_119")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_120")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55)))
		.pause(1)
		.exec(http("request_121")
			.get("/guri/pta/solicitar_matricula/gerarSolicitacaoMatricula/")
			.headers(headers_0))
		.pause(5)
		.exec(http("request_0")
			.get("https://" + uri1 + ":443/guri/")
			.headers(headers_0)
			.resources(http("request_1")
			.get("https://" + uri1 + ":443/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_2")
			.get("https://" + uri1 + ":443/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1)))
		

	}


	object Sair {
			val scnSair = exec(http("request_0")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.resources(http("request_1")
			.get("/guri/ptl/sistema/logout")
			.headers(headers_1),
            http("request_2")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_3")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_4")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_5")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_6")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_7")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_8")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_9")
			.get("/guri/application/modules/ptl/views/public/css/carrossel.css")
			.headers(headers_1),
            http("request_10")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_11")
			.get("/guri/public/js/jquery.price_format.1.0.js"),
            http("request_12")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js"),
            http("request_13")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js"),
            http("request_14")
			.get("/guri/public/js/jquery.cookie.js"),
            http("request_15")
			.get("/guri/public/js/jquery.dd.js"),
            http("request_16")
			.get("/guri/public/js/jquery.multifile.js"),
            http("request_17")
			.get("/guri/public/js/acessivel.js"),
            http("request_18")
			.get("/guri/public/js/angular.min.js"),
            http("request_19")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js"),
            http("request_20")
			.get("/guri/public/js/dialog_sessao.js"),
            http("request_21")
			.get("/guri/public/js/validacoes.js"),
            http("request_22")
			.get("/guri/public/js/admin.js"),
            http("request_23")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js"),
            http("request_24")
			.get("/guri/public/js/tabs.js"),
            http("request_25")
			.get("/guri/public/js/tabs.min.js"),
            http("request_26")
			.get("/guri/public/js/jquery-i18n/dicionario.js"),
            http("request_27")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js"),
            http("request_28")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js"),
            http("request_29")
			.get("/guri/public/js/select2/js/select2.min.js"),
            http("request_30")
			.get("/guri/public/js/jquery-i18n/tradutor.js"),
            http("request_31")
			.get("/guri/application/modules/ptl/views/public/js/login.js"),
            http("request_32")
			.get("/guri/application/modules/ptl/views/public/js/carrossel.js"),
            http("request_33")
			.get(uri2 + "")
			.headers(headers_10),
            http("request_34")
			.get("/guri/public/themes/moder/imgs/instrucoes.png"),
            http("request_35")
			.get("/guri/public/themes/moder/imgs/login.png"),
            http("request_36")
			.get("/guri/public/themes/moder/imgs/mapa-site.png"),
            http("request_37")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png"),
            http("request_38")
			.get("/guri/public/themes/moder/imgs/marca.png"),
            http("request_39")
			.get("/guri/public/themes/moder/imgs/contraste.png"),
            http("request_40")
			.get("/guri/public/themes/moder/imgs/logo_guri.png"),
            http("request_41")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png"),
            http("request_42")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png"),
            http("request_43")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png"),
            http("request_44")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png"),
            http("request_45")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png"),
            http("request_46")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif"),
            http("request_47")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png"),
            http("request_48")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif"),
            http("request_49")
			.get("/guri/public/themes/moder//imgs/help_verde.png"),
            http("request_50")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png"),
            http("request_51")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png"),
            http("request_52")
			.get("/guri/public/themes/moder//imgs/busca.png"),
            http("request_53")
			.get("/guri/public/themes/moder//imgs/novo_user.png"),
            http("request_54")
			.get("/guri/public/themes/moder//imgs/lock.png"),
            http("request_55")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png"),
            http("request_56")
			.get("/guri/public/themes/moder//imgs/favicon-guri16.png")
			.headers(headers_55)))

	}



val PURelatorio = scenario("SolicitacaoELogin").exec(Login.scnLogin, Relatorio.scngerarRelatorio, Sair.scnSair)
val PUMatriculadorERelatorio = scenario("SolicitacaoELogin").exec(Login.scnLogin, Solicitacao.scnSolicitarMatricula, Relatorio.scngerarRelatorio, Sair.scnSair)
val PUMatriculador = scenario("SolicitacaoELogin").exec(Login.scnLogin, Solicitacao.scnSolicitarMatricula, Sair.scnSair)
	setUp(
		PURelatorio.inject(atOnceUsers(1)),
		PUMatriculadorERelatorio.inject(atOnceUsers(1)),
		PUMatriculador.inject(atOnceUsers(1))
	).protocols(httpProtocol)

}